//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int MaLoai { get; set; }
        public Nullable<System.DateTime> NgaySX { get; set; }
        public string ThongSoKyThuat { get; set; }
        public Nullable<int> SoLo { get; set; }
        public Nullable<int> DonGia { get; set; }
    }
}
